# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  name "courier"
  desc "Blutui Courier CLI"
  homepage "https://blutui.com"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  on_macos do
    on_intel do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_mac-os_x86_64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "99d42cb491c08d71f78a3d2b28971780f0de36f37abb56498667fd9adb1b37a4"
    end
    on_arm do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_mac-os_arm64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "491a916e88a3be67250a2026c1a9352d8fa49b71c252e9abae9e991d3d1bf2bd"
    end
  end

  on_linux do
    on_intel do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_linux_x86_64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "ee3f3ec7c1a92b0f1e6bda1a7fbd14a064f84c0b827d731fd7b49476a5b256ad"
    end
    on_arm do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_linux_arm64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "d8f259f9776d6ec034bceb4cd3436891a83d84a5c76dba0a62b20319cea7cdd7"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/courier"]
    end
  end

  caveats do
    "Don't forget to add the .courier directory in your .gitignore file."
  end

  # No zap stanza required
end
