# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "cb37e2b2cdd88642193ad7d95ca43875849abddd4bd7d0b8e7659ee00ba8b0a3"
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_mac-os_x86_64.tar.gz",
        verified: "cdn.blutui.com/courier"
    end
    on_arm do
      sha256 "1674c03957d58873640efb6958fde8e1eecf4358b81b89481d00302f12c7d3d1"
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_mac-os_arm64.tar.gz",
        verified: "cdn.blutui.com/courier"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a9f493987b95f4a01f5aed33229ad9cc9cc065f73fe95ca3149ebda736107b8"
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_linux_x86_64.tar.gz",
        verified: "cdn.blutui.com/courier"
    end
    on_arm do
      sha256 "dcbad188e587eccae59d4519d43274fb383b367f7820946ced5d470b90d9db2b"
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_linux_arm64.tar.gz",
        verified: "cdn.blutui.com/courier"
    end
  end

  name "courier"
  desc "Blutui Courier CLI"
  homepage "https://blutui.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/courier"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Don't forget to add the .courier directory in your .gitignore file.
  EOS
end
