# This file was generated by GoReleaser. DO NOT EDIT.
cask "courier" do
  name "courier"
  desc "Blutui Courier CLI"
  homepage "https://blutui.com"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "courier"

  on_macos do
    on_intel do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_mac-os_x86_64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "e88c02edbdd49da4b43dcfed182f9f6108959287e4537e2a843e5dd8ce69e2e4"
    end
    on_arm do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_mac-os_arm64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "1e3616411fd9aeaffdb7acb815d24a6a1540acfdae01c07d56c4c39f0abd9d75"
    end
  end

  on_linux do
    on_intel do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_linux_x86_64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "a32697c29876c2da6d51bcbc1af904bdac555f492b6ae00aa0f04a909a9bdf94"
    end
    on_arm do
      url "https://cdn.blutui.com/courier/v#{version}/courier_#{version}_linux_arm64.tar.gz",
        verified: "cdn.blutui.com/courier"
      sha256 "e74800d84e9caf59b3a178f53d3842af59090424b762238d5d1c6497147d1718"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/courier"]
    end
  end

  caveats do
    "Don't forget to add the .courier directory in your .gitignore file."
  end

  # No zap stanza required
end
