# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Courier < Formula
  desc "Blutui Courier CLI"
  homepage "https://blutui.com"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://cdn.blutui.com/courier/v1.0.0/courier_1.0.0_macOS_64-bit.tar.gz"
      sha256 "ff428cec454fd2b24812f9b2c804a45e141ea060bb00614152b8da3acc6cc3a5"

      def install
        bin.install "courier"
      end
    end
    on_arm do
      url "https://cdn.blutui.com/courier/v1.0.0/courier_1.0.0_macOS_arm64.tar.gz"
      sha256 "87972d2431c499b66c9b18845fdbcf5c198f186cc1b71327d8c5e31df5a2e10d"

      def install
        bin.install "courier"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.blutui.com/courier/v1.0.0/courier_1.0.0_linux_64-bit.tar.gz"
        sha256 "8fe7f3181decbf2d8e52acbb5502199bbe69ba8738590a24607c6b07ab9f3167"

        def install
          bin.install "courier"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.blutui.com/courier/v1.0.0/courier_1.0.0_linux_arm64.tar.gz"
        sha256 "d7f83008aeb921f4a726415d3eee366de376dc463e2172364a276cd2a010986b"

        def install
          bin.install "courier"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Dont forget to add the .courier directory in your .gitignore file.
    EOS
  end
end
