# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Courier < Formula
  desc "Blutui Courier CLI"
  homepage "https://blutui.com"
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://cdn.blutui.com/courier/v1.1.0/courier_1.1.0_macOS_64-bit.tar.gz"
      sha256 "6dcf9b9e9c3cdb353e4fef163761bd73c228de89bcaf586dae959eef49254ae6"

      def install
        bin.install "courier"
      end
    end
    on_arm do
      url "https://cdn.blutui.com/courier/v1.1.0/courier_1.1.0_macOS_arm64.tar.gz"
      sha256 "fdf289781d8c62cd2d1b6da1485f3d5ffb79c5605f1591c4c28f3e756cca3558"

      def install
        bin.install "courier"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.blutui.com/courier/v1.1.0/courier_1.1.0_linux_64-bit.tar.gz"
        sha256 "16980d065ecff3e7886fc167d3b91eb00101db2bfcc959c96626abf56ecf60ae"

        def install
          bin.install "courier"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://cdn.blutui.com/courier/v1.1.0/courier_1.1.0_linux_arm64.tar.gz"
        sha256 "5b161e9f1d0bd6617ac2d6709a6f74c0a00415e166b13b194a42cc1f4f4298e2"

        def install
          bin.install "courier"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Dont forget to add the .courier directory in your .gitignore file.
    EOS
  end
end
