# This file was generated by GoReleaser. DO NOT EDIT.
class Courier < Formula
  desc "Blutui Courier CLI"
  homepage "https://blutui.com"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://cdn.blutui.com/courier/v0.2.0/courier_0.2.0_macOS_64-bit.tar.gz"
    sha256 "16ef44f488e96ca7167648a0d7e4c2a1e89183d687b7718d88d65366a8a439e7"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://cdn.blutui.com/courier/v0.2.0/courier_0.2.0_linux_64-bit.tar.gz"
      sha256 "edeb4f186e2fc68fce4b38ad2c024bbc27afcb76984c6245182c5af7dcd2cb54"
    end
  end

  def install
    bin.install "courier"
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
